networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
########################### SERVICES
include:
  # - SERVICE-PLACEHOLDER-DO-NOT-DELETE
  - /home/bfrost/docker/compose/$HOSTNAME/custom.yml
  - /home/bfrost/docker/compose/$HOSTNAME/portainer.yml
  - /home/bfrost/docker/compose/$HOSTNAME/socket-proxy.yml
  - /home/bfrost/docker/compose/$HOSTNAME/mariadb.yml
  - /home/bfrost/docker/compose/$HOSTNAME/authelia.yml
  - /home/bfrost/docker/compose/$HOSTNAME/traefik.yml
  # SERVICE-PLACEHOLDER-DO-NOT-DELETE
