version: "3.9"
networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
########################### SERVICES
include:
  # - SERVICE-PLACEHOLDER-DO-NOT-DELETE
  - compose/$HOSTNAME/custom.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/mariadb.yml
  - compose/$HOSTNAME/authelia.yml
  - compose/$HOSTNAME/traefik.yml
  # SERVICE-PLACEHOLDER-DO-NOT-DELETE
