networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
########################### SERVICES
include:
  # - SERVICE-PLACEHOLDER-DO-NOT-DELETE
  - /home/bfrost/docker/compose/pepper/custom.yml
  - /home/bfrost/docker/compose/pepper/portainer.yml
  - /home/bfrost/docker/compose/pepper/socket-proxy.yml
  - /home/bfrost/docker/compose/pepper/mariadb.yml
  - /home/bfrost/docker/compose/pepper/authelia.yml
  - /home/bfrost/docker/compose/pepper/traefik.yml
  # SERVICE-PLACEHOLDER-DO-NOT-DELETE
