version: "3.9"

########################### NETWORKS
# There is no need to create any networks outside this docker-compose file.
# You may customize the network subnets (192.168.90.0/24 and 91.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

########################### SERVICES
include:
  - compose/socket-proxy.yml
  # - compose/custom.yml
  - compose/traefik.yml
  - compose/portainer.yml
  - compose/dozzle.yml
  - compose/homepage.yml
  - compose/uptime-kuma.yml
  # - SERVICE-PLACEHOLDER-DO-NOT-DELETE
