services:
  NAME:
    image: REPLACE
    container_name: NAME
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t2_proxy
      - default
    # ports:
    #  - "3001:3001" 
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/NAME:/app/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.NAME-rtr.entrypoints=https"
      - "traefik.http.routers.NAME-rtr.rule=Host(`NAME.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.NAME-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.NAME-rtr.service=NAME-svc"
      - "traefik.http.services.NAME-svc.loadbalancer.server.port=BACKENDPORT"
