services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t2_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      fpm: false
    volumes:
      - $DOCKERDIR/appdata/organizr:/config
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.organizr-rtr.entrypoints=https"
      # - "traefik.http.routers.organizr-rtr.rule=Host(`$DOMAINNAME`)"
      - "traefik.http.routers.homepage-rtr.rule=Host(`$DOMAINNAME`,`www.$DOMAINNAME`)" # Both domain.com and www.domain.com
      ## Middlewares
      - "traefik.http.routers.organizr-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.organizr-rtr.service=organizr-svc"
      - "traefik.http.services.NorganizrME-svc.loadbalancer.server.port=80"