services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command: tunnel run
    profiles: ["apps", "all"]
    networks:
      - t2_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      TUNNEL_TOKEN: $CF_CLOUDFLARED   
    volumes:
      - $DOCKERDIR/appdata/NAME:/app/data
