services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      LOG_LEVEL: info
      LOG_JSON: false
    command: serve
    volumes:
      - $DOCKERDIR/appdata/diun/data:/data
      - $DOCKERDIR/appdata/diun/config:/etc/diun
      - /var/run/docker.sock:/var/run/docker.sock