services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    hostname: Hostname
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t2_proxy
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      KOPIA_SERVER_USERNAME: $DOCKER_USERNAME
      KOPIA_SERVER_PASSWORD: $TM_PASSWORD
      SECRET_REPO_PASSWORD: $REPO
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/kopia:/app
      # - $DOCKERDIR/appdata/kopia/config:/app/config
      # - $DOCKERDIR/appdata/kopia/cache:/app/cache
      # - $DOCKERDIR/appdata/kopia/logs:/app/logs
      - /mnt:/data:ro
      - /mnt/media/kopia:/repository
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.koipa-rtr.tls=true"
      - "traefik.http.routers.kopia-rtr.entrypoints=websecure"
      - "traefik.http.routers.kopia-rtr.rule=Host(`kopia.$DOMAINNAME`)"
      - "traefik.http.routers.kopia-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.kopia-rtr.service=kopia-svc"
      - "traefik.http.services.kopia-svc.loadbalancer.server.port=51515"