services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t2_proxy
      - socket_proxy
      - default
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      fpm: false
    volumes:
      - $DOCKERDIR/appdata/organizr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr-rtr.entrypoints=websecure"
      - "traefik.http.routers.organizr-rtr.rule=Host(`$DOMAINNAME`,`www.$DOMAINNAME`,`organizr.$DOMAINNAME`)"
      # - "traefik.http.routers.organizr-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.organizr-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.organizr-rtr.service=organizr-svc"
      - "traefik.http.services.organizr-svc.loadbalancer.server.port=80"