services:
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    network_mode: host
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_MODS: linuxserver/mods:plex-absolute-hama
      VERSION: public
      PLEX_CLAIM: ${PLEX_CLAIM_CODE}
    volumes:
      - /mnt/ramdisk:/transcode
      - $DOCKERDIR/appdata/plex:/config
      - "$DOCKERDIR/appdata/plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle:/usr/lib/plexmediaserver/Resources/Plug-ins-f05b712b6/Trakttv.bundle"
      - /mnt/media/tv:/data/tvshows
      - /mnt/media/tvdvr:/data/tvdvr
      - /mnt/media/gphotos/photos:/data/photos
      - /mnt/media/movies:/data/movies