services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    user: 1000:1000
    volumes:
      - $DOCKERDIR/appdata/recyclarr:/config
    environment:
      TZ: $TZ
      RECYCLARR_CREATE_CONFIG: "true"