services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      # - t2_proxy
      - default
      # - socket_proxy
    # ports:
    #  - "3001:3001" 
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      RECYCLARR_CREATE_CONFIG: "true"
    user: $PUID:$PGID
    volumes:
      - $DOCKERDIR/appdata/recyclarr:/config