services:
  speedtest:
    image:  lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t2_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      OOKLA_EULA_GDPR: true
      DB_CONNECTION: sqlite
      PUBLIC_DASHBOARD: true
      APP_KEY: $SPEEDTEST_KEY
    volumes:
      - $DOCKERDIR/appdata/speedtest:/config
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.speedtest-rtr.entrypoints=websecure"
      - "traefik.http.routers.speedtest-rtr.rule=Host(`speedtest.$DOMAINNAME`)"
      ## Middlewares
      # - "traefik.http.routers.speedtest-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.speedtest-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.speedtest-rtr.service=speedtest-svc"
      - "traefik.http.services.speedtest-svc.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"