services:
  syslogng:
    image: linuxserver/syslog-ng:4.5.0
    container_name: syslogng
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
    ports:
      - 6601:6601/tcp # Syslog TCP
      # - 6514:6514/tcp # Syslog TLS
      - 5514:5514/udp # Syslog UDP
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/syslogng:/config