services:
  uptimekuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t2_proxy
      # - default
      - socket_proxy
    # ports:
    #  - "3001:3001" 
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/uptimekuma:/app/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma-rtr.tls=true"
      ## HTTP Routers
      - "traefik.http.routers.uptimekuma-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma-rtr.rule=Host(`uptimekuma.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.uptimekuma-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.uptimekuma-rtr.service=uptimekuma-svc"
      - "traefik.http.services.uptimekuma-svc.loadbalancer.server.port=3001"
